steps:
- name: 'node:20.12.1'
  entrypoint: 'npm'
  args: ['ci']
- name: node:20.12.1
  entrypoint: npx
  args: ['bundage', 'bfn', 'dev/main', 'main_bin', '-t', 'bin']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/phading-dev/video-formatting-job:latest', '-f', 'dev/Dockerfile', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/phading-dev/video-formatting-job:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'jobs', 'replace', 'dev/service.yaml']
options:
  logging: CLOUD_LOGGING_ONLY
