apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: video-formatting-job
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      template:
        spec:
          maxRetries: 1
          timeoutSeconds: 3600
          serviceAccountName: video-formatting-account@phading-dev.iam.gserviceaccount.com
          containers:
          - name: video-formatting-job-container
            image: gcr.io/phading-dev/video-formatting-job:latest
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
            env:
            - name: gcsFilename
              value: ""
            - name: localMasterPlaylistName
              value: ""
            - name: localPlaylistName
              value: ""
            - name: videoDirOptional
              value: ""
            - name: audioDirs
              value: ""
            volumeMounts:
            - name: gcs-input-volume
              mountPath: /gcs_video
              readOnly: true
            - name: gcs-output-volume
              mountPath: /gcs_video_output
              readOnly: false
          volumes:
          - name: gcs-input-volume
            csi:
              driver: gcsfuse.run.googleapis.com
              readOnly: true
              volumeAttributes:
                bucketName: phading-dev-video
          - name: gcs-output-volume
            csi:
              driver: gcsfuse.run.googleapis.com
              readOnly: false
              volumeAttributes:
                bucketName: phading-dev-video-output
